app_lucky_number:
    path: /lucky/number/{firstname}/{lastname}
    controller: App\Controller\LuckyController::number
    defaults:
        firstname: Jean
        lastname: Dupond

hellopage:
    path: /hello
    controller: App\Controller\LuckyController::hello